version: "3"

services:
  dev-go-beta:
    build: ./
    environment:
      GOPRIVATE: github.com/kami988/*
      GITHUB_USER_NAME: ${GITHUB_USER_NAME}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_EMAIL: ${GITHUB_EMAIL}
    volumes:
      - "kami988.learning.go-beta:/repo"
      - "kami988.learning.go.1.18beta2:/go"
    tty: true

volumes:
  kami988.learning.go-beta:
  kami988.learning.go.1.18beta2: